### ISSUE TITLE
Unused Parameter Warnings

### ISSUE THREAD

**Issue by MrBurmark** [NVIDIA/cub#187]
When compiling cub 1.8.0 with clang 9 (not nvcc) with the cuda 9.1 toolkit I encounter a large number of unused parameter warnings.
I looked at the master branch and found that many of these parameters are still unused.

Example warnings:
```
/home/raja/tpl/cub/cub/device/dispatch/../../agent/../thread/../util_ptx.cuh:273:57: warning: unused parameter 'member_mask' [-Wunused-parameter]

__device__  __forceinline__ void WARP_SYNC(unsigned int member_mask)

                                                        ^
/home/raja/tpl/cub/cub/device/dispatch/../../agent/agent_radix_sort_downsweep.cuh:311:37: warning: unused parameter 'valid_items' [-Wunused-parameter]

        OffsetT                     valid_items,

                                    ^
```

Example fix:
```
template <typename ... Ts >
void ignore_unused(Ts&&...)
{ }

void foo(int bar, int baz)
{
  ignore_unused(bar, baz);
}
```

**Comment by himanshu007-creator** [comment]
I would like to work on this issue, Please provide me the file to be changed and what needs to be changed

**Comment by allisonvacanti** [comment]
It's hard to say exactly what needs to be changed, outside of the two warnings reported. This would require downloading and building the CUDA C++ source code and test suite, see what warnings are emitted during compilation, and fixing them as they come up.

This might be more complicated though. I fixed several other unused parameter warnings in a recent warning cleanup, but it looks like our CI didn't catch all of them. We need to look at whether we missed them due to an issue with our build system or if it's a lack of test coverage.

**Comment by himanshu007-creator** [comment]
okay, Then i guess its not a <code>good first issue</code>

**Comment by allisonvacanti** [comment]
It made more sense when it was reported :) Fixing some warnings is a good first issue for someone familiar with CUDA development, but unfamiliar with CUB.

But now it looks like it will take some investigation into why we missed these warnings on CI, and I agree -- I'll remove that tag 👍

**Comment by allisonvacanti** [comment]
We've done a number of warning-cleanup passes recently, and this should not be an issue anymore when built against supported CTKs (11.0+).
