### ISSUE TITLE
Compile fails with anonymous namespace CUB_NS_PREFIX

### ISSUE THREAD

**Issue by llehtahw** [NVIDIA/cub#222]
reproduce:
``` cuda
#define CUB_NS_PREFIX namespace {
#define CUB_NS_POSTFIX }
#include <cub/cub.cuh>
int main()
{
        int res = (int)cub::Equals<int, int>::VALUE;
        return res;
}
```

```
/workspace/abc/a.cu(6): error: "cub" is ambiguous

/workspace/abc/a.cu(6): error: expected an identifier

/workspace/abc/a.cu(6): error: expected a ";"
```

Seems that [these lines](https://github.com/NVIDIA/cub/commit/629f01ec7b4f660d293899ab84680fb7819ece42#diff-b5b693806476b576b12bffce3bbe3cd6dca2326f0544c5cfb55083ff81736867R54-R57) introduced the errors.

**Comment by allisonvacanti** [comment]
Can confirm:

`1.8.0`: https://www.godbolt.org/z/fjrP7K
`main`: https://www.godbolt.org/z/4K98Pc

We'll also need to add a test for this.

**Comment by elstehle** [comment]
I believe this is due to this one here. The doxygen declaration just ignores the macro.
https://github.com/NVIDIA/cub/blob/ea48955fe5814b2319f77a68bd7094f5fdbf1b08/cub/util_namespace.cuh#L56

I have had a fix for this a few months ago but forgot to push upstream. It got lost with repo move now. I can contribute later tonight, unless you want to take it on, @allisonvacanti

**Comment by allisonvacanti** [comment]
Awesome -- Contributions are more than welcome. I probably wouldn't get to this for a couple of days, so if you have a branch ready to push, go for it :)
