### ISSUE TITLE
run fail after compile with "-G" for  the example_block_reduce.cu source file

### ISSUE THREAD

**Issue by YinLiu-91** [NVIDIA/cub#267]
When I compile the source file use  the "nvcc  -G -g  example_block_reduce.cu -I../.. -lcudart -o block_reduce" command ,it can successfully got a binary file ,but it run fail . And when I delete  "-G" ,it run successfully. There is also the same error for "...block_san.cu" and "example_device_sort_find_non_trivial_runs.cu"

**Comment by allisonvacanti** [comment]
Compiling with device debugging is problematic with heavily templated code like CUB -- I'm surprised you managed to compile without running out of memory! It's not a well-tested compilation mode for CUB.

Usually full device debugging (`-G`) is heavy-handed for most debugging needs, we usually just use `nvcc --lineinfo` ([docs](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-altering-compiler-linker-behavior-generate-line-info)). This generates enough info to debug without causing compilation / runtime issues.

Try using `--lineinfo` instead of `-G` and see if that gives you what you need. If that doesn't work for your needs, feel free to reopen and share some more about your usecase.
