### ISSUE TITLE
Version question

### ISSUE THREAD

**Issue by peetw** [NVIDIA/cub#273]
Hi,

On the releases page, it states that cub 1.12.0 supports CUDA Toolkit 11.4 and that cub 1.11.0 supports CUDA Toolkit 11.3. However, as far as I'm aware, the latest released version of CUDA Toolkit is 11.2.2. I'm guessing those referenced CUDA versions are currently pre-release?

I guess my main question is that we've just upgraded to CUDA Toolkit 11.2.2 and I'm wondering whether we should be using the latest release of cub (i.e. 1.12.0), or the one that supports CUDA 11.2 (i.e. 1.10.0)?

**Comment by peetw** [comment]
Ah, I'd forgotten that cub is now bundled with the CUDA Toolkit (1.10.0 with CUDA 11.2.2) and trying to use a later version of cub fails with the following error:

`1>C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/include\thrust/system/cuda/config.h(78): fatal error C1189: #error:  The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.`

I'll probably stick with the bundled version, but is there any danger in using a newer version of cub if say you wanted to take advantage of some the improvements/fixes?

**Comment by allisonvacanti** [comment]
> I'm guessing those referenced CUDA versions are currently pre-release?

Yes. The CUDA Toolkit release process is much longer than ours, so new releases of Thrust and CUB usually aren't available in CTK for a few cycles.

> I'm wondering whether we should be using the latest release of cub (i.e. 1.12.0), or the one that supports CUDA 11.2 (i.e. 1.10.0)?

It depends on what you need.

Thrust and CUB ship with the CUDA Toolkit for convenience -- if your code doesn't benefit from using the newer version, sticking with the version provided by CTK will be easier for you and your users since there's no extra dependencies to install.

If you need fixes or features from a newer version, pulling a github branch is your best option.

> Is there any danger in using a newer version of cub if say you wanted to take advantage of some the improvements/fixes?

Thrust and CUB are inter-dependent and are version-locked to each other as a result. Things *may* work if you mix Thrust/CUB versions, but it's not supported and will likely break at some point -- especially as we tackle some of the larger refactorings that are planned.

If you want to use a newer version of CUB, your best bet is to use that version of Thrust from Github, since it provides a git submodule pointing to a compatible CUB and you won't have to worry about mismatches. If you use CMake, it will set up the paths correctly so you won't have to worry about pulling in older versions of headers from a CTK install.

Closing, but feel free to reopen if you have more questions.
