### ISSUE TITLE
BlockReduce incorrect result / ignoring certain thread values

### ISSUE THREAD

**Issue by MatthiasKohl** [NVIDIA/cub#344]
I have an example where I noticed cub is giving wrong results.
On further investigation, it looks like the `BlockReduce::Sum` function from cub is "ignoring" values from certain threads, but it's a bit erratic.
Here is the gist, with an example with 64 threads / block and 33 threads holding non-zero values:
https://gist.github.com/MatthiasKohl/f84cfba617ec6edf6a21e9bbc69f57fe

I'm using Ubuntu 16.04 (64-bit) and CUDA 11.3, see the exact version and compile command in the gist.
It feels like a compiler issue, but I don't have time to investigate any deeper.

Specifying how many threads participate in the reduction does not change the results, for me.

EDIT: forgot to mention that the tests I did were on V100 (PCIE 16GB)

**Comment by senior-zero** [comment]
Hello, @MatthiasKohl! 

There are two issues in your gist. First of all, it should be

```cuda
auto &red_storage = *reinterpret_cast<typename BlockReduce::TempStorage*>(smem);
```

rather than:
```cuda
auto red_storage = *reinterpret_cast<typename BlockReduce::TempStorage*>(smem);
```

You've created a thread-local copy of TempStorage, so threads of the same block couldn't communicate with each other using it. Using the reference fixes your case. 

Apart from that, you [can't estimate](https://forums.developer.nvidia.com/t/how-can-one-determine-the-temp-storage-size-for-cub-block-primitives-from-the-host/112839) the temporary storage size from the host side, because CUB uses `CUB_PTX_ARCH` macro. As a workaround you could manually specify the architecture:

```cuda
auto smem_size = sizeof(typename cub::BlockReduce<float, TPB, cub::BLOCK_REDUCE_WARP_REDUCTIONS, 1, 1, 700>::TempStorage);

```

With these fixes, your gist works fine, so I'm closing the issue. Please, feel free to reopen it if there is anything I've overlooked.

**Comment by MatthiasKohl** [comment]
Thanks for looking into this!
May I suggest adding an overload of the constructor for `BlockReduce` which works somehow nicely with dynamic shared memory?
It's a common use-case in order to re-use shared memory, but to me, it seems like it's not really made for this.

**Comment by gonzalobg** [comment]
> May I suggest adding an overload of the constructor for BlockReduce which works somehow nicely with dynamic shared memory?

+1. That would allow just passing the pointer to shared memory. The current approach requires dereferencing the pointer just for the purpose of creating a reference to the value behind the pointer.

**Comment by allisonvacanti** [comment]
> The current approach requires dereferencing the pointer

Just to be clear -- this doesn't actually dereference the pointer or access any data, it just repackages the pointer as a reference.

I'm not sure I see the value of adding duplicate constructors here. If we added pointer overloads, they would still be strongly typed and you'd have to cast anyway. You'd just be casting to a `TempStorage*` instead of a `TempStorage&`.

**Comment by MatthiasKohl** [comment]
> You'd just be casting to a TempStorage* instead of a TempStorage&.

Personally, casting to a `TempStorage&` feels wrong, since there isn't really an object you're referencing (this is *usually* the case with references).
This is why using the pointer feels more explicit and natural to me, but I can't speak for everyone, so I just wanted to let you know.

In any case, I think it would be great to have an example in the docs showing the use of dynamic shared memory with objects such as `BlockReduce`. I'd be open to add this if you think it's worth it.

**Comment by allisonvacanti** [comment]
> In any case, I think it would be great to have an example in the docs showing the use of dynamic shared memory with objects such as BlockReduce. I'd be open to add this if you think it's worth it.

Absolutely -- feel free to push a PR, I think this would be quite valuable to have.
