### ISSUE TITLE
Missing <iterator> include in util_type.cuh

### ISSUE THREAD

**Issue by maddyscientist** [NVIDIA/cub#435]
The recent changes as a part of the 1.16 work, specifically, 68f51a93831bc423562d5a9b398165778339f077, introduced the use of `std::iterator_traits`.  E.g., [here](https://github.com/NVIDIA/cub/commit/68f51a93831bc423562d5a9b398165778339f077#diff-7883605f0f62cb7979093529c93a2d067adba8c1a3cc115de5adc2882297a595R78).  However, the header `iterator` was not included, and this leads to breakages.  Specifically, this change break QUDA when compiled with Jitify / NVRTC.

The simple fix is to ensure that `<iterator>` is included in all files that utilize `std::iterator_traits`.  A quick look at the source, suggests that beyond `util_type.cuh`, potentially `device/dispatch/dispatch_unique_by_key.cuh` and `device/dispatch/dispatch_adjacent_difference.cuh` have a potential issue in this regard.

**Comment by allisonvacanti** [comment]
Thanks for testing the RC!

Dug into it a bit. I was surprised since we compile all headers by themselves to prevent this sort of thing. But it looks like `nvcc` pulls in portions of `iterator_traits` as part of its default `--pre-include`'d header set, so this slipped under the radar.

We'll fix this and tag a new RC. I'll also see about fixing our header tests to avoid the pre-included headers, if possible.
