### ISSUE TITLE
Link pointing to Thrust Development Model in CONTRIBUTING.md is invalid (gives 404)

### ISSUE THREAD

**Issue by kshitij12345** [NVIDIA/cub#447]
Ref: https://github.com/NVIDIA/cub/blob/main/CONTRIBUTING.md#development-model

**Comment by allisonvacanti** [comment]
Thanks for pointing this out! The Thrust docs were reorganized recently and we missed this.

This link should point to https://github.com/NVIDIA/thrust/blob/main/docs/github_pages/releases/versioning.md.

**Comment by kshitij12345** [comment]
Should the PR be on this repo or thrust? Sorry I am a bit confused.

**Comment by kshitij12345** [comment]
Also, link to CONTRIBUTING.md of thrust is invalid

Ref: https://github.com/NVIDIA/cub/blob/main/CONTRIBUTING.md#contributing-to-cub

**Comment by allisonvacanti** [comment]
Great, thanks for the PR :)

On second thought, we should probably link to the new formatted docs rather than the markdown files. Can you update #449 so that:

1. "development model" link goes to https://nvidia.github.io/thrust/releases/versioning.html
2. "contributing" link goes to https://nvidia.github.io/thrust/contributing.html

Thanks!
