### ISSUE TITLE
Figure out why there are three versions of `block_scan_warp_scans.cuh`

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cub#467]
In `cub/block/specializations/`:

```
block_scan_warp_scans.cuh
block_scan_warp_scans2.cuh
block_scan_warp_scans3.cuh
```

Only the unversioned file is used, but we should check the difference between these and remove the old ones if they're not needed anymore.

**Comment by allisonvacanti** [comment]
@dumerrill let us know if you have any insights/opinions on these files or if there's any value in keeping them around.

**Comment by senior-zero** [comment]
I believe those two specializations to be research leftovers:
- First of all, there's no way to use them at user side. If block_scan_warp_scans{,2,3}.cuh used if-guards, there would be a way to switch implementations, but not now. All structures are called `BlockScanWarpScans`, so they can't coexist. 
- Our tests don't pass with those implementations. For block_scan_warp_scans2.cuh this is caused by a different logic behind block aggregate computation. Our current implementation doesn't include `initial_value` into the `block_aggregate`, whereas block_scan_warp_scans2.cuh does. 
- Judging on the git history, those specializations hasn't been used. 

I've compared performance and both block_scan_warp_scans{2,3}.cuh are slower. Since they are slower, don't conform to the current API and hasn't been tested, I'm going to remove these files for 2.0. I consider everything in the specialization folder to be a detail, so I don't think we should mark this as a breaking change. 

If there's an interest in the differences between implementation, here's a high-level overview:

First steps of all implementations are similar:

1. Performs warp scan
2. Last thread of a warp stores warp aggregate in shared memory

The subsequent steps differ, though:

Current implementation:

1. All threads in all warps read partial aggregates of all warps from shared memory to compute warp prefix/block aggregate with no cooperation

Implementation 2

1. Lanes with `lane_id < N_WARPS` read data from shared memory cooperatively and apply another warp scan to compute warp prefix/block aggregate
2. Results of the previous operation are communicated to other threads with broadcast 

Implementation 3

1. Lanes with `lane_id < N_WARPS` read data from shared memory cooperatively and apply another warp scan to compute warp prefix/block aggregate
2. Results of the previous operation are written into shared memory
3. All threads read aggregates from shared memory

**Comment by allisonvacanti** [comment]
Thanks for checking into this, I agree with the resolution.
