### ISSUE TITLE
AdjacentDifferenceCopy not following stl adjacent difference requirement

### ISSUE THREAD

**Issue by vince-streamhpc** [NVIDIA/cub#507]
The definition `std::adjacent_difference` specifies that the `BinaryOperation op` is called exactly once to determine the output.
https://en.cppreference.com/w/cpp/algorithm/adjacent_difference
```
Performs *d_first = *first;. For every d in [1, last - first - 1], assigns *(first + d) - *(first + d - 1) (overload (2)) or op(*(first + d), *(first + d - 1)) (overload (4)) to *(d_first + d).
```
From this follows that `op()` should not be invoked twice to get the output.

However, an operator that looks like the following would show that it is invoked twice:
```cpp
template<class T>
struct flag_expected_op : public std::binary_function<T, T, discard_write<T>>{
    bool left;
    T expected;
    T expected_above_limit;
    int* d_flags;
    flag_expected_op(bool left, T expected, T expected_above_limit, int* d_flags) :
    left(left), expected(expected), expected_above_limit(expected_above_limit), d_flags(d_flags){
    }

    __host__ __device__ int operator()(const discard_write<T>& minuend, const discard_write<T>& subtrahend) {
        if(left)
        {
            if(minuend == expected && subtrahend == expected - 1)
            {
                ++d_flags[0];
            }
            if(minuend == expected_above_limit && subtrahend == expected_above_limit - 1)
            {
                ++d_flags[1];
            }
        }
        else
        {
            if(minuend == expected && subtrahend == expected + 1)
            {
                ++d_flags[0];
            }
            if(minuend == expected_above_limit && subtrahend == expected_above_limit + 1)
            {
                ++d_flags[1];
            }
        }
        return 0;
    }
};
```

Is it intended to follow the stl definition of `std::adjacent_difference` or can this not be classified as a `bug`?

**Comment by Maetveis** [comment]
Thanks @senior-zero, the fix helps, the first call to `SubtractLeftCopy` (meant to get the memory requirements) no longer launches the algorithm, but the problem still exists. When the problem size is not divisible by `items_per_tile` the user supplied operator is called with values (and more times overall) than what the standard specifies (altough cub documentation does not explicitly make the same guarantee).

I have a more complete example here:
```cuda
#include <cub/device/device_adjacent_difference.cuh>
#include <cub/iterator/counting_input_iterator.cuh>

#include <thrust/device_vector.h>
#include <thrust/host_vector.h>

#include <iostream>

int main() {
    static constexpr unsigned int size = 10;

    std::size_t temp_storage_size = 0;
    void* d_temp_storage = nullptr;

    cub::CountingInputIterator<unsigned int> input(0);
    thrust::device_vector<unsigned int> d_output(size, 0);
    thrust::device_vector<unsigned int> d_side_effect(size, 0);

    const auto op = [iter = d_side_effect.begin()] __device__ (unsigned int right, unsigned int/* left*/) 
        { atomicAdd((&iter[right]).get(), 1); return right; };
    cub::DeviceAdjacentDifference::SubtractLeftCopy(d_temp_storage, temp_storage_size, input, d_output.begin(), size, op);

    cudaMalloc(&d_temp_storage, temp_storage_size);
    cub::DeviceAdjacentDifference::SubtractLeftCopy(d_temp_storage, temp_storage_size, input, d_output.begin(), size, op);

    thrust::host_vector<unsigned int> side_effect = d_side_effect;
    for(const auto& i : side_effect) {
        std::cerr << i << '\n';
    }
    cudaFree(d_temp_storage);
}
```
Compiled with `nvcc -std=c++14 --extended-lambda -I cub/ -I thrust/ main.cu`, with your branch of cub and latest thrust (be34b50c637ce081ddf2789833c8f4d7845c2a18 at the time of writing).

The output is: `886 1 1 1 1 1 1 1 1 1`
But `0 1 1 1 1 1 1 1 1 1` is expected, because the operator should be called exactly 9 times, with the values [1,9] for the parameter `right`.

I suspect the problem is in [agent_adjcacent_difference.cuh on line 130](https://github.com/NVIDIA/cub/blob/main/cub/agent/agent_adjacent_difference.cuh#L130) where incomplete tiles are filled with the first value of the tile, and the `*PartialTile` APIs of `BlockAdjacentDifference` are not used.

**Comment by senior-zero** [comment]
@Maetveis thank you for your comment! I've updated the PR with a commit that fixes this. I also added new test to check the number of operator invocations.
